import{a as S,S as q,i as l}from"./assets/vendor-KnZd4sWe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="48999193-84142b43a51cfa1138f8dc0d5",P="https://pixabay.com/api/";async function p(s,t){try{return(await S.get(P,{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}})).data}catch(o){return console.error("Error while searching for images",o),{hits:[],totalHits:0}}}const u=document.querySelector(".gallery");function m(s,t=!1){t||(u.innerHTML="");const o=s.map(({webformatURL:e,largeImageURL:r,tags:i,likes:h,views:b,comments:L,downloads:w})=>`<li class="gallery-item">
            <a href="${r}" class="gallery-link">
             <img src="${e}" class="gallery-img" alt="${i}"/>
              <div class="img-info">
              <p>Likes: ${h}</p>
              <p>Views: ${b}</p>
              <p>Comments: ${L}</p>
              <p>Downloads: ${w}</p>
              </div>
            </a>
           </li>`).join("");u.insertAdjacentHTML("beforeend",o),new q(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const $=document.querySelector(".form"),H=document.querySelector(".input"),g=document.querySelector(".loading"),f=document.querySelector(".gallery"),c=document.querySelector(".load-btn");let y="",n=1,d=0;$.addEventListener("submit",async s=>{if(s.preventDefault(),y=H.value.trim(),y===""){l.warning({message:"Please enter a keyword to search"});return}f.innerHTML="",n=1,c.style.display="none",g.style.display="block",console.log("Loader on");try{const t=await p(y,n);d=t.totalHits;const o=t.hits;if(o.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}m(o),n*40<d&&(c.style.display="block")}catch{l.error({message:"Something went wrong. Please try again later."})}finally{g.style.display="none",console.log("Loader off")}});c.addEventListener("click",async()=>{n+=1,g.style.display="block",console.log("Loader on");try{const t=(await p(y,n)).hits;if(t.length===0){c.style.display="none";return}m(t,!0);const a=f.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),(n-1)*40+t.length>=d&&(c.style.display="none",l.info({message:"We are sorry, but you have reached the end of search results."}))}catch{l.error({message:"Something went wrong. Please try again later."})}finally{g.style.display="none",console.log("Loader off")}});
//# sourceMappingURL=index.js.map
